import javax.swing.JOptionPane;
/**
 *
 * @author laiba
 */
public class Reservation extends javax.swing.JFrame {

    /**
     * Creates new form Reservation
     */
    public Reservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        passengers2Field = new javax.swing.JTextField();
        passengers2 = new javax.swing.JLabel();
        amountpaid2field = new javax.swing.JTextField();
        confirmbutton = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();
        from2field = new javax.swing.JTextField();
        to2field = new javax.swing.JTextField();
        doj2Field = new javax.swing.JTextField();
        doj2 = new javax.swing.JLabel();
        dep2field = new javax.swing.JTextField();
        T_type1Field = new javax.swing.JTextField();
        class2Field = new javax.swing.JTextField();
        amountpaid2 = new javax.swing.JLabel();
        class2 = new javax.swing.JLabel();
        T_type1 = new javax.swing.JLabel();
        dep2 = new javax.swing.JLabel();
        To2 = new javax.swing.JLabel();
        From2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        doj1 = new javax.swing.JLabel();
        dep1 = new javax.swing.JLabel();
        dest = new javax.swing.JLabel();
        ticket_type1 = new javax.swing.JLabel();
        class1 = new javax.swing.JLabel();
        passengers1 = new javax.swing.JLabel();
        dest1field = new javax.swing.JComboBox<>();
        dep1field = new javax.swing.JComboBox<>();
        SingleButton = new javax.swing.JRadioButton();
        ReturnButton = new javax.swing.JRadioButton();
        FirstClassButton = new javax.swing.JRadioButton();
        EconomyButton = new javax.swing.JRadioButton();
        passengers1Field = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        submit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        total1 = new javax.swing.JLabel();
        tax1 = new javax.swing.JLabel();
        sub_total1 = new javax.swing.JLabel();
        total1Field = new javax.swing.JTextField();
        tax1field = new javax.swing.JTextField();
        SubTotalField1 = new javax.swing.JTextField();
        review = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        passengers2Field1 = new javax.swing.JTextField();
        passengers3 = new javax.swing.JLabel();
        amountpaid2field1 = new javax.swing.JTextField();
        confirmbutton1 = new javax.swing.JButton();
        exitbutton1 = new javax.swing.JButton();
        from2field1 = new javax.swing.JTextField();
        to2field1 = new javax.swing.JTextField();
        doj2Field1 = new javax.swing.JTextField();
        doj3 = new javax.swing.JLabel();
        dep2field1 = new javax.swing.JTextField();
        T_type1Field1 = new javax.swing.JTextField();
        class2Field1 = new javax.swing.JTextField();
        amountpaid3 = new javax.swing.JLabel();
        class3 = new javax.swing.JLabel();
        T_type2 = new javax.swing.JLabel();
        dep3 = new javax.swing.JLabel();
        To3 = new javax.swing.JLabel();
        From3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        passengers2Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passengers2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengers2FieldActionPerformed(evt);
            }
        });

        passengers2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passengers2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        passengers2.setText("NUMBER OF PASSENGERS");

        amountpaid2field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        confirmbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        confirmbutton.setText("CONFRIM");
        confirmbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbuttonActionPerformed(evt);
            }
        });

        exitbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitbutton.setText("EXIT");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });

        from2field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        from2field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from2fieldActionPerformed(evt);
            }
        });

        to2field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        to2field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to2fieldActionPerformed(evt);
            }
        });

        doj2Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        doj2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doj2FieldActionPerformed(evt);
            }
        });

        doj2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        doj2.setText("DATE OF JOURNEY");

        dep2field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        T_type1Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        class2Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        amountpaid2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amountpaid2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        amountpaid2.setText("AMOUNT PAID");

        class2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        class2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        class2.setText("CLASS");

        T_type1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        T_type1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        T_type1.setText("TICKET TYPE");

        dep2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dep2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dep2.setText("DEPARTURE");

        To2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        To2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        To2.setText("TO");

        From2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        From2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        From2.setText("FROM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REVIEW PORTAL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T_type1)
                    .addComponent(dep2)
                    .addComponent(doj2)
                    .addComponent(From2)
                    .addComponent(To2)
                    .addComponent(class2)
                    .addComponent(passengers2)
                    .addComponent(amountpaid2))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dep2field, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T_type1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doj2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to2field, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(from2field, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(class2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passengers2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountpaid2field, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(confirmbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(from2field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(From2))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(to2field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(To2))
                                .addGap(31, 31, 31)
                                .addComponent(doj2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(doj2))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dep2field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dep2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(T_type1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(T_type1))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(class2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(class2))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passengers2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passengers2))
                        .addGap(33, 33, 33)
                        .addComponent(amountpaid2field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(amountpaid2))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmbutton)
                    .addComponent(exitbutton))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESERVE YOUR TICKET");

        doj1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        doj1.setText("DATE OF JOURNEY");

        dep1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dep1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dep1.setText("DEPARTURE");

        dest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dest.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dest.setText("DESTINATION");

        ticket_type1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ticket_type1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ticket_type1.setText("TICKET TYPE");

        class1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        class1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        class1.setText("CLASS");

        passengers1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passengers1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        passengers1.setText("NUMBER OF PASSENGERS");

        dest1field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dest1field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lahore", "Peshawar", "Karachi", "Kashmir", "Multan" }));
        dest1field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dest1fieldActionPerformed(evt);
            }
        });

        dep1field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dep1field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:30am", "10:30am", "8:30pm" }));
        dep1field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dep1fieldActionPerformed(evt);
            }
        });

        SingleButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SingleButton.setText("SINGLE");
        SingleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingleButtonActionPerformed(evt);
            }
        });

        ReturnButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ReturnButton.setText("RETURN");
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        FirstClassButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FirstClassButton.setText("FIRST CLASS");
        FirstClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstClassButtonActionPerformed(evt);
            }
        });

        EconomyButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EconomyButton.setText("ECONOMY");

        passengers1Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passengers1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengers1FieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dest, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doj1)
                    .addComponent(dep1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passengers1)
                    .addComponent(class1)
                    .addComponent(ticket_type1))
                .addGap(128, 128, 128)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SingleButton)
                        .addGap(52, 52, 52)
                        .addComponent(ReturnButton, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                    .addComponent(dep1field, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(FirstClassButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EconomyButton))
                    .addComponent(passengers1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dest1field, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(class1)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dest1field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doj1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dep1field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dep1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SingleButton)
                            .addComponent(ReturnButton)
                            .addComponent(ticket_type1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstClassButton)
                            .addComponent(EconomyButton))
                        .addGap(3, 3, 3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passengers1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passengers1))
                .addContainerGap())
        );

        submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        total1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        total1.setText("TOTAL");

        tax1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tax1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tax1.setText("TAX");

        sub_total1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sub_total1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sub_total1.setText("SUB TOTAL");

        total1Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total1FieldActionPerformed(evt);
            }
        });

        tax1field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        SubTotalField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total1)
                    .addComponent(tax1)
                    .addComponent(sub_total1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tax1field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total1Field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubTotalField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total1)
                    .addComponent(total1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tax1)
                    .addComponent(tax1field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sub_total1)
                    .addComponent(SubTotalField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        review.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        review.setText("REVIEW");
        review.setActionCommand("REVIEW");
        review.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewActionPerformed(evt);
            }
        });

        passengers2Field1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passengers2Field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengers2Field1ActionPerformed(evt);
            }
        });

        passengers3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passengers3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        passengers3.setText("NUMBER OF PASSENGERS");

        amountpaid2field1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        confirmbutton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        confirmbutton1.setText("CONFRIM");
        confirmbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbutton1ActionPerformed(evt);
            }
        });

        exitbutton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitbutton1.setText("EXIT");
        exitbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbutton1ActionPerformed(evt);
            }
        });

        from2field1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        from2field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from2field1ActionPerformed(evt);
            }
        });

        to2field1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        to2field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to2field1ActionPerformed(evt);
            }
        });

        doj2Field1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        doj2Field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doj2Field1ActionPerformed(evt);
            }
        });

        doj3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        doj3.setText("DATE OF JOURNEY");

        dep2field1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        T_type1Field1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        class2Field1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        class2Field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class2Field1ActionPerformed(evt);
            }
        });

        amountpaid3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amountpaid3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        amountpaid3.setText("AMOUNT PAID");

        class3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        class3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        class3.setText("CLASS");

        T_type2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        T_type2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        T_type2.setText("TICKET TYPE");

        dep3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dep3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dep3.setText("DEPARTURE");

        To3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        To3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        To3.setText("TO");

        From3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        From3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        From3.setText("FROM");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REVIEW PORTAL");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(From3)
                    .addComponent(doj3)
                    .addComponent(To3)
                    .addComponent(passengers3)
                    .addComponent(amountpaid3)
                    .addComponent(T_type2)
                    .addComponent(dep3)
                    .addComponent(class3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(to2field1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(from2field1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doj2Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dep2field1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(class2Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passengers2Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountpaid2field1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T_type1Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(confirmbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(From3)
                            .addComponent(from2field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(to2field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(To3))
                        .addGap(59, 59, 59))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doj3)
                        .addComponent(doj2Field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dep3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dep2field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(T_type2)
                    .addComponent(T_type1Field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(class3))
                    .addComponent(class2Field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passengers3)
                    .addComponent(passengers2Field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountpaid3)
                    .addComponent(amountpaid2field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmbutton1)
                    .addComponent(exitbutton1))
                .addGap(34, 34, 34))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("MAIN MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(273, 273, 273)
                                .addComponent(submit))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(review))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jButton1)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(submit)
                        .addGap(58, 58, 58)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(review)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dest1fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dest1fieldActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_dest1fieldActionPerformed

    private void dep1fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dep1fieldActionPerformed

    }//GEN-LAST:event_dep1fieldActionPerformed

    private void SingleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingleButtonActionPerformed

    }//GEN-LAST:event_SingleButtonActionPerformed

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnButtonActionPerformed

    private void FirstClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstClassButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstClassButtonActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void total1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total1FieldActionPerformed

    private void reviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reviewActionPerformed

    private void passengers2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengers2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passengers2FieldActionPerformed

    private void confirmbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbuttonActionPerformed
        JOptionPane.showMessageDialog(null,"Your Ticket is Reserved");
        
    }//GEN-LAST:event_confirmbuttonActionPerformed

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        // TODO add your handling code here:
        Reservation r = new Reservation();
        r.setVisible(true);
    }//GEN-LAST:event_exitbuttonActionPerformed

    private void from2fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from2fieldActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_from2fieldActionPerformed

    private void to2fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to2fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_to2fieldActionPerformed

    private void doj2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doj2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doj2FieldActionPerformed

    private void passengers2Field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengers2Field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passengers2Field1ActionPerformed

    private void confirmbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbutton1ActionPerformed
        JOptionPane.showMessageDialog(null,"Your Ticket is Reserved");
        
    }//GEN-LAST:event_confirmbutton1ActionPerformed

    private void exitbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbutton1ActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_exitbutton1ActionPerformed

    private void from2field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from2field1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_from2field1ActionPerformed

    private void to2field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to2field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_to2field1ActionPerformed

    private void doj2Field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doj2Field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doj2Field1ActionPerformed

    private void class2Field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class2Field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_class2Field1ActionPerformed

    private void passengers1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengers1FieldActionPerformed
        passengers1Field.setOpaque(true);
    }//GEN-LAST:event_passengers1FieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         WelcomePage w = new WelcomePage();
        w.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton EconomyButton;
    private javax.swing.JRadioButton FirstClassButton;
    private javax.swing.JLabel From2;
    private javax.swing.JLabel From3;
    private javax.swing.JRadioButton ReturnButton;
    private javax.swing.JRadioButton SingleButton;
    private javax.swing.JTextField SubTotalField1;
    private javax.swing.JLabel T_type1;
    private javax.swing.JTextField T_type1Field;
    private javax.swing.JTextField T_type1Field1;
    private javax.swing.JLabel T_type2;
    private javax.swing.JLabel To2;
    private javax.swing.JLabel To3;
    private javax.swing.JLabel amountpaid2;
    private javax.swing.JTextField amountpaid2field;
    private javax.swing.JTextField amountpaid2field1;
    private javax.swing.JLabel amountpaid3;
    private javax.swing.JLabel class1;
    private javax.swing.JLabel class2;
    private javax.swing.JTextField class2Field;
    private javax.swing.JTextField class2Field1;
    private javax.swing.JLabel class3;
    private javax.swing.JButton confirmbutton;
    private javax.swing.JButton confirmbutton1;
    private javax.swing.JLabel dep1;
    private javax.swing.JComboBox<String> dep1field;
    private javax.swing.JLabel dep2;
    private javax.swing.JTextField dep2field;
    private javax.swing.JTextField dep2field1;
    private javax.swing.JLabel dep3;
    private javax.swing.JLabel dest;
    private javax.swing.JComboBox<String> dest1field;
    private javax.swing.JLabel doj1;
    private javax.swing.JLabel doj2;
    private javax.swing.JTextField doj2Field;
    private javax.swing.JTextField doj2Field1;
    private javax.swing.JLabel doj3;
    private javax.swing.JButton exitbutton;
    private javax.swing.JButton exitbutton1;
    private javax.swing.JTextField from2field;
    private javax.swing.JTextField from2field1;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel passengers1;
    private javax.swing.JTextField passengers1Field;
    private javax.swing.JLabel passengers2;
    private javax.swing.JTextField passengers2Field;
    private javax.swing.JTextField passengers2Field1;
    private javax.swing.JLabel passengers3;
    private javax.swing.JButton review;
    private javax.swing.JLabel sub_total1;
    private javax.swing.JButton submit;
    private javax.swing.JLabel tax1;
    private javax.swing.JTextField tax1field;
    private javax.swing.JLabel ticket_type1;
    private javax.swing.JTextField to2field;
    private javax.swing.JTextField to2field1;
    private javax.swing.JLabel total1;
    private javax.swing.JTextField total1Field;
    // End of variables declaration//GEN-END:variables
}
